Add files in .gitignore
simphony/simphony-ui pull request #16
Opened 2017-03-03 15:50 UTC by martinRenou

2017-03-03 16:37 UTC, stefanoborini requested changes

2017-03-03 16:37 UTC, stefanoborini commented on .gitignore
> +simphony_ui/couple_CFDDEM.pyc
Put *.pyc instead of the individual pyc files.

2017-03-03 17:37 UTC, martinRenou commented
Changes done

2017-03-05 05:21 UTC, stefanoborini commented
Ok. i fixed the cache thing, but at this point the PR is doing two unrelated things. so as an exercise try to get the .travis.yml changes in a separate PR, build that, merge it to master, then merge master back here.

2017-03-06 10:24 UTC, stefanoborini approved these changes

2017-03-06 10:49 UTC, merged