Replace default mayavi modules by custom modules
simphony/simphony-ui pull request #53
Opened 2017-03-23 18:29 UTC by martinRenou

2017-03-24 16:09 UTC, stefanoborini requested changes

2017-03-24 16:09 UTC, stefanoborini commented on simphony_ui/ui.py
> +            max_radius = numpy.max(numpy.array(
If there's no radius, it will throw an exception.

2017-03-24 16:09 UTC, stefanoborini commented on simphony_ui/ui.py
> +        max_velocity = numpy.max(velocities)
What happens if max_velocity is zero?

2017-03-24 16:09 UTC, stefanoborini commented on simphony_ui/ui.py
> +            arrow_scale_factor = 20.0 * max_radius/max_velocity
if max_radius is zero, you will obtain a scale factor of zero.

2017-03-24 16:10 UTC, stefanoborini requested changes

2017-03-24 16:10 UTC, stefanoborini commented on simphony_ui/ui.py
> +            1
1.0

2017-03-24 16:10 UTC, stefanoborini requested changes

2017-03-24 16:10 UTC, stefanoborini commented on simphony_ui/ui.py
> +        sphere_glyph_module.glyph.glyph.range = [0, 1]
floating points

2017-03-27 09:13 UTC, stefanoborini requested changes

2017-03-27 09:13 UTC, stefanoborini commented on simphony_ui/ui.py
> +            return
If the openfoam_wrapper is None, you probably have to clear the scene as well.

2017-03-27 09:13 UTC, stefanoborini commented on simphony_ui/ui.py
> +        if self.liggghts_wrapper is None:
same

2017-03-27 09:13 UTC, stefanoborini commented on simphony_ui/ui.py
> +            arrow_scale_factor = 50000.0
I think we should write as a comment something like: velocities are in whatever unit. This conversion factor makes 1 graphical unit = x velocity units.

The question is: what is the velocity unit? I'll see if I find it (doubt it, without checking the output)

2017-03-27 09:13 UTC, stefanoborini commented on simphony_ui/ui.py
> +            arrow_scale_factor = 50000.0
Openfoam units are metric, so it's meter/second.

2017-03-27 09:16 UTC, stefanoborini commented on simphony_ui/ui.py
> +            arrow_scale_factor = 50000.0
which means that we are working in the range of tens of micrometers/sec. I would be tempted to say 1 gu = 1 micrometer/sec. That will make arrows probably good enough for all purposes.

2017-03-27 09:20 UTC, martinRenou commented on simphony_ui/ui.py
> +            arrow_scale_factor = 50000.0
Ok thanks :)

2017-03-27 12:22 UTC, stefanoborini approved these changes

2017-03-27 12:22 UTC, merged